# Generated by Django 5.1.7 on 2025-03-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Breakfast', max_length=200)),
                ('foodFoto', models.ImageField(upload_to='img')),
            ],
        ),
    ]
