# Generated by Django 5.1.7 on 2025-03-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlists',
            name='foodFoto',
            field=models.ImageField(upload_to='foto'),
        ),
    ]
