# Generated by Django 5.1.7 on 2025-03-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pps', '0003_drink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='drink',
            new_name='drinkmodel',
        ),
    ]
