# Generated by Django 5.1.6 on 2025-03-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pps', '0008_remove_drinkitem_bstatus_drinkitem_dstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='quntity',
            field=models.IntegerField(default=0),
        ),
    ]
