# Generated by Django 5.1.6 on 2025-03-23 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pps', '0011_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_at',
            new_name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='custemer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drink_items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='food_items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='need_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pohone_No',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
