# Generated by Django 5.1.6 on 2025-04-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pps', '0013_order_customer_name_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkitem',
            name='type',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink')], default='drink', max_length=20),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='type',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink')], default='food', max_length=20),
        ),
    ]
