# Generated by Django 5.1.6 on 2025-04-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pps', '0014_drinkitem_type_fooditem_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkitem',
            old_name='quntity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
