# Generated by Django 5.2 on 2025-04-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pps', '0015_rename_quntity_drinkitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
