# Generated by Django 5.2 on 2025-04-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pps', '0016_order_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hidden_for_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
