# Generated by Django 5.2 on 2025-04-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pps', '0017_order_hidden_for_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hidden_for_user',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
